Skyscanner/cfripper

cfripper/rules/CrossAccountTrustRule.py

The principal can be a condition which will crash the check.

Fix CrossAcount rule bug

---

setup.py

Fixes #24 
The goal is to allow cfripper to be used as a library as a PyPI package. Currently, the setup process is not including sub-directories.
This PR fixes it.

Find project packages

---

cfripper/config/config.py
tests/test_main.py

The current `get_stack_exemption_list` method returns right after finding the first matching expression in the whitelist, this causes a bug where the following whitelist wouldn't work:
```
stack_whitelist = {
"stack*": [
"Rule1",
"Rule2",
],
"stackname": [
"Rule3",
"Rule4",
],
```
Because the stack with name `stackname` would only be whitelisted for Rule1 and RUle2, not Rule3 and Rule4. This change fixes this issue and updates the variable names for clarity.
- Renamed `get_exemption_list` to `get_whitelisted_rules`
- Fixed `get_whitelisted_rules` to get all whitelists that match the stack name instead of the first one
- Added test to check that the functionality works as expected.

Update method to get whitelisted rules for a stack

---

cfripper/model/enums.py
cfripper/model/result.py
cfripper/model/rule.py
cfripper/model/rule_processor.py
tests/test_rule_processor.py

Following the update to having a generic whitelist for resources and another one for actions, this update adds the option to add a list of resource_ids and/or actions to the failure.
It also introduces the concept of failure granularity, each failure has a granularity which can be:
- Stack: Applies to all stack
- Resource: Applies to a set of resources in the stack
- Action: Applies to a set of actions in the stack
The new methods added in the rule processor will use the granularity of the failure along with the new whitelists that were already added to filter the failures that contain affect ONLY whitelisted resources or failures according to the failure granularity.
- Added a granularity enum
- Added methods to remove whitelisted failures and resources to the rule processor, the methods …

Add resource and action to failure, use generic whitelists to remove whitelisted failures

---

.travis.yml
cfripper/main.py
cfripper/model/result.py
cfripper/model/rule_processor.py
setup.py
tests/test_cross_account.py
tests/test_main.py
tests/test_rule_cloud_formation_authentication.py
tests/test_rule_cross_account_trust.py
tests/test_rule_hardcoded_rds_password.py
tests/test_rule_iam_managed_policy_wildcard_action.py
tests/test_rule_iam_wildcard_on_trust_policy.py
tests/test_rule_processor.py
tests/test_rule_security_group_missing_egress.py
tests/test_rules_iam_roles_overprivileged.py
tests/test_rules_s3_bucket_wildcard_action.py
tests/test_rules_s3_read_plus_list.py
tests/test_rules_security_group_open_to_world.py
tests/test_rules_sqs_policy_public.py
tests/test_rules_sqs_policy_wildcard.py
tests/test_s3_cross_account.py

Fix issue when calling CFRipper as a lambda.
It would fail due to sets not being serialized properly

Fix serialization bug in lambda handler usage

---

cfripper/rules/CrossAccountTrustRule.py
setup.py
tests/rules/test_CrossAccountTrustRule.py
tests/test_templates/rules/CrossAccountTrustRule/valid_with_service.json

CrossAccountRule could say that a role has forbidden cross-account trust relationship with an AWS service like `lambda.amazonaws.com`.

[BUGFIX] Fix CrossAccountRule when trust relationship contains a service

---

CHANGELOG.md
cfripper/config/config.py
cfripper/config/regex.py
cfripper/config/whitelist.py
cfripper/model/utils.py
cfripper/rules/S3BucketPolicyPrincipalRule.py
cfripper/rules/S3CrossAccountTrustRule.py
setup.py
tests/config/test_regex.py
tests/rules/test_S3BucketPolicyPrincipalRule.py
tests/rules/test_S3CrossAccountTrustRule.py
tests/test_templates/rules/S3BucketPolicyPrincipalRule/bad_template.json
tests/test_templates/rules/S3CrossAccountTrustRule/s3_bucket_cross_account_from_aws_service.json

This PR adds ELB service accounts and makes sure S3 bucket rules don't trigger due to the inclusion of any of this accounts in a bucket policy

Add AWS ELB service account whitelist

---

cfripper/model/result.py
tests/model/test_result.py

The valid attribute was previously being updated as rules were added.
Now that we have resource whitelisting and we remove the failures after adding them this method of calculating valid doesn't work anymore.
Update `valid` attribute to be a property, results are only valid if they don't have Blocking rules.

Add valid as a property in Result class

---

CHANGELOG.md
cfripper/rules/HardcodedRDSPasswordRule.py
tests/rules/test_HardcodedRDSPasswordRule.py
tests/test_templates/rules/HardcodedRDSPasswordRule/bad_clusters_and_instances.json
tests/test_templates/rules/HardcodedRDSPasswordRule/bad_template_cluster.json
tests/test_templates/rules/HardcodedRDSPasswordRule/rds_good_cluster_bad_instances.json
tests/test_templates/rules/HardcodedRDSPasswordRule/rds_good_cluster_good_instances.json

CFRipper will currently flag stacks as invalid when an RDS Instance is being created without a master password set or missing `NoEcho`. However, the rule does not take into consideration RDS Clusters being created with a correct password policy, and instances being part of that cluster. In those cases, the instances inherit the password policy from the cluster, and it is should be a valid CloudFormation file.
- Update to `HardcodedRDSPasswordRule` to look at both Clusters and Instances for misconfigurations
- The rule now tracks clusters with passwords set correctly, and checks each instance to see if it is part of a protected cluster or not
- Tests added for each use case below:
- 1x misconfigured RDS instance (invalid)
- 1x misconfigured RDS cluster (invalid)
- 1x protected RDS instance …

Add hardcoded password check for AWS RDS Clusters

---

CHANGELOG.md
cfripper/rules/CrossAccountTrustRule.py
tests/rules/test_CrossAccountTrustRule.py

We had no visibility on when an AWS Account ID was not set in the config (for whatever reason).
Add a logging statement for when an account ID is not present in the config, which affects the ability of the `CrossAccountTrust` rule to run. Test for logging statement also added.

Add logging for case where AWS Account ID is not present in the config

---

CHANGELOG.md
cfripper/rules/hardcoded_RDS_password.py
setup.py
tests/rules/test_HardcodedRDSPasswordRule.py

- `HardcodedRDSPasswordRule` now reports two different messages when there is a missing echo or a readable password.
- `HardcodedRDSPasswordRule` was wrongly adding an error when a value is provided.

Fix harcoded password rds rule

---

cfripper/rules/hardcoded_RDS_password.py

Fixed mis-spelling of cluster in hardcoded RDS password rule.

Fixed spelling mistake in hardcoded_RDS_password.py rule

---

CHANGELOG.md
cfripper/rules/__init__.py
cfripper/rules/base_rules.py
cfripper/rules/cloudformation_authentication.py
cfripper/rules/cross_account_trust.py
cfripper/rules/ebs_volume_has_sse.py
cfripper/rules/hardcoded_RDS_password.py
cfripper/rules/iam_managed_policy_wildcard_action.py
cfripper/rules/iam_roles.py
cfripper/rules/kms_key_wildcard_principal.py
cfripper/rules/managed_policy_on_user.py
cfripper/rules/policy_on_user.py
cfripper/rules/privilege_escalation.py
cfripper/rules/s3_bucket_policy.py
cfripper/rules/s3_public_access.py
cfripper/rules/security_group.py
cfripper/rules/sns_topic_policy_not_principal.py
cfripper/rules/sqs_queue_policy.py
cfripper/rules/wildcard_principals.py
setup.py
tests/rules/test_CrossAccountTrustRule.py
tests/rules/test_GenericWildcardPrincipal.py
tests/test_templates/rules/CrossAccountTrustRule/kms_basic.yml
tests/utils.py

- `KMSKeyCrossAccountTrustRule`
- `GenericWildcardPrincipalRule`, `PartialWildcardPrincipalRule`, `FullWildcardPrincipalRule` no longer check for
wildcards in KMSKey principals.
- Improved granularity of most rules 
Besides this, I've refactored the rule `__init__` file and this has surfaced a few non-default rules. We need to discuss what to do with those.

Improve kms handling and rule granularity

---

CHANGELOG.md
cfripper/__version__.py
cfripper/config/regex.py
cfripper/model/utils.py
tests/config/test_regex.py
tests/rules/test_CrossAccountTrustRule.py
tests/test_templates/rules/CrossAccountTrustRule/invalid_with_sts.yml
tests/test_templates/rules/CrossAccountTrustRule/valid_with_sts.yml

- Fix for `CrossAccountCheckingRule` was adding errors when the principal was sts when it shouldn't. 
- `get_account_id_from_sts_arn` and `get_aws_service_from_arn` in utils.

Accepts sts for principals in `CrossAccountCheckingRule` rules

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/__init__.py
cfripper/rules/kms_key_wildcard_principal.py
cfripper/rules/security_group.py
tests/rules/test_SecurityGroupIngressOpenToWorld.py

- Generate DEFAULT_RULES and BASE_CLASSES using code instead of hardcoding
- Whitelist did not work if it didn't have the `Rule` prefix
- Sufix `KMSKeyWildcardPrincipal` and `SecurityGroupIngressOpenToWorld` with `Rule`
- Sufix whitelist constant `FullWildcardPrincipal` and `PartialWildcardPrincipal` with `Rule`

Refactor rules name and fix whitelist

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/security_group.py
requirements.txt
setup.py
tests/rules/test_SecurityGroupIngressOpenToWorld.py
tests/test_templates/rules/SecurityGroupIngressOpenToWorld/good_template.json
tests/test_templates/rules/SecurityGroupOpenToWorldRule/invalid_security_group_multiple_statements.json
tests/test_templates/rules/SecurityGroupOpenToWorldRule/invalid_security_group_range.json

This PR uses the latest updates in `pycfmodel` to improve the current rules for checking publicly open security groups. Before, the rule only blocked on `/0` CIDR blocks. It now uses the Python `ipaddress` library to natively check if an CIDR block `is_global` or not.
|        IP        |    Before   |    After    |
|:---------------:|:-----------:|:-----------:|
|   `0.0.0.0/0`   |   blocked   |   blocked   |
|   `10.0.0.0/8`  | not blocked | not blocked |
|   `11.0.0.0/8`  | not blocked |   blocked   |
|      `::/0`     |   blocked   |   blocked   |
| `172.16.0.0/12` | not blocked | not blocked |
|     `fa::/8`    | not blocked |   blocked   |

Improve scope of Sec Group Ingress and Open Ports rule

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/cross_account_trust.py
docs/macros.py
docs/rule_config.md
tests/rules/test_CrossAccountTrustRule.py

- `CrossAccountCheckingRule`, `CrossAccountTrustRule`, `S3CrossAccountTrustRule` and `KMSKeyCrossAccountTrustRule` include support for filters.
- `CrossAccountCheckingRule` now includes the invoke method. Statements of PolicyDocument are now analysed using `RESOURCE_TYPE` and `PROPERTY_WITH_POLICYDOCUMENT` class variables.

Implement filters in CrossAccount Rules + Refactor of these inherit classes

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/security_group.py
tests/rules/test_SecurityGroupIngressOpenToWorld.py
tests/rules/test_SecurityGroupOpenToWorldRule.py

- Improved message for users when failing the `SecurityGroupOpenToWorldRule` and `SecurityGroupIngressOpenToWorldRule` rules.
- Improved documentation for the above rules, including styling fixes which have now been tested.

Improve message and documentation for security group rules

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/cross_account_trust.py

- `CrossAccountCheckingRule` calling `add_failure_to_result` on `UNDEFINED_` was missing context variable.

Fix for add_failure on cross_account

---

CHANGELOG.md
cfripper/__version__.py
cfripper/main.py
cfripper/model/result.py
cfripper/rules/cloudformation_authentication.py
cfripper/rules/ebs_volume_has_sse.py
cfripper/rules/ec2_security_group.py
cfripper/rules/iam_roles.py
cfripper/rules/managed_policy_on_user.py
cfripper/rules/policy_on_user.py
cfripper/rules/s3_bucket_policy.py
cfripper/rules/s3_public_access.py
cfripper/rules/sns_topic_policy_not_principal.py
cfripper/rules/sqs_queue_policy.py
cfripper/rules/wildcard_policies.py
cfripper/rules/wildcard_principals.py
tests/rules/test_CloudFormationAuthenticationRule.py
tests/rules/test_EBSVolumeHasSSERule.py
tests/rules/test_EC2SecurityGroupMissingEgressRule.py
tests/rules/test_GenericWildcardPrincipal.py
tests/rules/test_IAMRoleWildcardActionOnPolicyRule.py
tests/rules/test_ManagedPolicyOnUserRule.py
tests/rules/test_PartialWildcardPrincipal.py
tests/rules/test_PolicyOnUserRule.py
tests/rules/test_S3BucketPublicReadAclAndListStatementRule.py
tests/rules/test_SNSTopicPolicyNotPrincipalRule.py
tests/rules/test_SQSQueuePolicyNotPrincipalRule.py
tests/rules/test_WildcardPoliciesRule.py

This change updates the `RULE_MODE` to `BLOCKING` for all the rules.
Now that the `rules_config` param can be passed to the `Config` class and it allows to modify the default modes of all rules easily, we can set them all to block by default so clients can update the modes of each rule to fit their preferences by using the `rules_config` param.
- Removed the rule_mode from the rules definitions, so now all rule modes are BLOCKING which is the default
- Updated tests to reflect rule mode changes
- Fixed linting issues surfaced from updating flake8 from 3.7 to 3.8

Update default rule modes to Blocking

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/ec2_security_group.py
tests/rules/test_EC2SecurityGroupIngressOpenToWorld.py

For rules where evaluation on the output via the use of filters is happening on `SecurityGroupIngressProperties` and `SecurityGroupIngressProp` objects, add an additional field to output just the Ipv4Network or IpV6Network string. This allows config objects containing the filters to be JSON serialisable without the need for converting between the string and network types.
**Any filters currently using `ingress`** will need to be updated to use `ingress_obj`, as shown in the updated test case:
```javascript
{"and": [{"eq": [{"ref": "config.stack_name"}, "mockstack"]}, {"eq": [{"ref": "ingress_obj.FromPort"}, 46]}]},
```
Example usage of the new filter field:
```javascript
{"in": [{"ref": "ingress_ip"}, ["11.0.0.0/8", "::/0"]]},
```

Modify ingress filter field to split into `ingress_obj` and `ingress_ip`

---

cfripper/cli.py
cfripper/config/config.py
tests/config/test_config.py
tests/rules/test_CrossAccountTrustRule.py

Running a command like this:
```bash
cfripper good_template.json --rules-config-file filter.py
Analysing tests/test_templates/rules/EC2SecurityGroupIngressOpenToWorld/good_template.json...
Unhandled exception raised, please create an issue with the error message at https://github.com/Skyscanner/cfripper/issues
Traceback (most recent call last):
File "/Users/olivercrawford/projects/cfripper_public/cfripper/cfripper/cli.py", line 175, in cli
for template in templates
File "/Users/olivercrawford/projects/cfripper_public/cfripper/cfripper/cli.py", line 175, in <listcomp>
for template in templates
File "/Users/olivercrawford/projects/cfripper_public/cfripper/cfripper/cli.py", line 105, in process_template
config, rule_processor = init_cfripper(rules_config_file)
File …
```

Rules config filter flag to use `TextIOWrapper` and not string

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/base_rules.py
cfripper/rules/privilege_escalation.py
tests/rules/test_PrivilegeEscalationRule.py
tests/test_templates/rules/PrivilegeEscalationRule/privilege_escalation_s3_bucket_policy.yaml

Some stacks were being marked as invalid by the `PrivilegeEscalation` rule as they contained dangerous IAM actions. Whilst this is true due to the use of `Action:*`, for some resources the context is not correct in which it is being applied. One example is an `S3BucketPolicy`:
```yml
TestBucketPolicy:
Type: AWS::S3::BucketPolicy
Properties:
Bucket: !Ref SomeS3Bucket
PolicyDocument:
Version: 2008-10-17
Statement:
- Sid: Stmt123456789012
Effect: Allow
Principal:
{
CanonicalUser: 1234abcd5678,
AWS: "arn:aws:iam::123456789012:role/s3-bucket-foo-bar-role",
}
Action: "*"
Resource: "arn:aws:s3:::my-bucket-of-potatoes"
- Sid: Stmt987654321345
Effect: Allow
Principal:
{
CanonicalUser: 1234abcd5678,
AWS: "arn:aws:iam::123456789012:role/s3-bucket-foo-bar-role",
}
Action: "*"
Resource: …
```

Update `ResourceSpecificRule` to allow for certain resources to be excluded

---

README.md
cfripper/config/rule_configs/example_rules_config_for_cli.py
cfripper/config/rule_configs/firehose_ips.py
tests/config/test_filter.py
tests/test_templates/config/security_group_firehose_ips.json

This PR adds an example `RuleConfig` to make CFRipper not flag valid AWS IPs when scanning a template containing a security group (usually for AWS Redshift). More information about access between Kinesis Data Firehose and Redshift can be found on this link:
https://docs.aws.amazon.com/firehose/latest/dev/controlling-access.html#using-iam-rs
Changes:
- updated README to include a simple HOWTO on using the `--rules-config-file` flag on the CLI
- Firehose specific rule filter for the `EC2SecurityGroupOpenToWorldRule` added, and shown in a complete example
- unit tests added
There should be **no** functional changes to CFRipper from this PR. The filter is not automatically applied unless added to the `RuleConfig` when running CFRipper.
Additionally, the CLI is not currently working as …

Rule Config for Kinesis Data Firehose IPs

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/wildcard_resource_rule.py
tests/rules/test_WildcardResourceRule.py

This rule may occasionally throw a false positive on some stacks where the Policy Document contains a `Resource: *` but the whole policy is actually being limited to a subset of AWS Resources. For example, we have SQS Queue Policies and SNS Topic Policies that are applied specifically to only some queues or topics respectively.
```yml
SQSQueuePolicy:
Type: 'AWS::SQS::QueuePolicy'
Properties:
PolicyDocument:
Statement:
- Sid: 'Look Dangerous; Be Nice'
Effect: Allow
Principal:
AWS: '*'
Action:
- sqs:*
Resource: '*'
Queues:
- !Ref MyAwesomeSQSQueue
```
There will be no functional changes to CFRipper from this PR - only subclasses or custom rules that use the `EXCLUDED_RESOURCE_TYPES` property will be impacted.
Change involved changing the parent class of this rule to use …

Update Wildcard Resource rule to allow for certain resources to be excluded

---

CHANGELOG.md
cfripper/__version__.py
cfripper/boto3_client.py
tests/test_boto3_client.py

Add exception handling around the following two events:
- receiving a `Throttling` exception when getting a template from CloudFormation (the retry mechanism is already in place along with a backoff mechanism)
- receiving a `AccessDenied` exception when listing export values (for example if the IAM role does not have permission to read these)
Unit tests updated and version + CHANGELOG bumped to 1.0.1

Update boto3_client to handle known exceptions from AWS more gracefully

---

CHANGELOG.md
cfripper/__version__.py
cfripper/boto3_client.py
tests/test_boto3_client.py

This PR:
- supports exception handling when we receive a throttling error from AWS during `list_exports`
- make functions sleep on first receipt of throttling exception (before, we were doing `sleep(0)`)
Unit tests updated and CHANGELOG and version bumped to 1.0.2

Add handling for AWS throttling when listing exports

---

CHANGELOG.md
cfripper/__version__.py
cfripper/boto3_client.py
tests/test_boto3_client.py

This PR is a minor update to the logging severity for this use case from exception to warning as it could generate a lot of noise when running. Unit test updated and CHANGELOG and version bumped to 1.0.3

Downgrade logging severity from exception to warning when there is no stack in AWS

---

CHANGELOG.md
cfripper/__version__.py
cfripper/boto3_client.py
cfripper/model/utils.py
tests/test_boto3_client.py

This PR:
- updates the logs to output the stack_id (if known) when failing to convert a template to JSON
- this will aid debugging as currently it is very difficult to track down which templates have caused issues
- added one unit test for coverage
CHANGELOG and version bumped to 1.0.4

Add stack ID to output of logger when we fail to convert YML template to JSON

---

cfripper/cli.py
docs/cli.md
tests/config/test_config.py
tests/rules/test_S3CrossAccountTrustRule.py
tests/test_cli.py
tests/test_templates/rules/S3CrossAccountTrustRule/s3_bucket_cross_account_and_normal.json

Whilst using CF Ripper on the command line I noticed I would get warnings such as:
`Not adding S3CrossAccountTrustRule failure in GrapplerBatchArchiveBucketPolicy because no AWS Account ID was found in the config`
And issues/errors such as:
`S3BucketPolicyPrincipalRule: S3 Bucket GrapplerBatchArchiveBucketPolicy policy has non-allowed principals <AWS Account ID>`
However, in the docs there was no way to set these from the command line. This would allow more checking locally on the CLI than having to build it into a pipeline and help find errors further to the left whilst developing.

Add CLI args for aws account id and aws principals

---

cfripper/rules/s3_public_access.py
tests/rules/test_S3BucketPublicReadAclAndListStatementRule.py

The following line in the rule from this commit is:
`bucket = cfmodel.Resources.get(bucket_name)`
It expects `bucket_name` to be a hashable object eg. string; however, for an
unresolved template at this point is will be a FunctionDict Ref at its most
basic which does not hash, and this will crash this rule.
This commit will provide a warning to the user that there may be a failure but it is not adding the rule until it is resolved, else it will crash.

Catch and warn about a rule crash in S3BucketPublicReadAclAndListStatementRule

---

tests/test_templates/rules/S3CrossAccountTrustRule/s3_bucket_cross_account.json

The root of this was quickly found by setting `GenericResource.ALLOW_EXISTING_TYPES = False`, which defaults to True in pycfmodel's GenericResource
It may be a good idea to set this to `False` for all tests so that you are using the type of object you expect.

Fix failing test_S3CrossAccountTrustRule.py::test_s3_bucket_cross_account

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/__init__.py
cfripper/rules/kms_key_rotation_enabled.py
requirements.txt
setup.py
tests/rules/test_KMSEnabledKeyRotationRule.py
tests/rules/test_S3BucketPublicReadAclRule.py
tests/test_templates/rules/KMSEnabledKeyRotation/bad_template_symmetric_keyspec_property.yaml
tests/test_templates/rules/KMSEnabledKeyRotation/bad_template_symmetric_no_property.yaml
tests/test_templates/rules/KMSEnabledKeyRotation/bad_template_symmetric_property.yaml

* New rule to check `EnableKeyRotation` for symmetric KMS keys.
* Bump `pycfmodel` to `0.10.4`

EnableKeyRotation rule for KMS

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/__init__.py
cfripper/rules/s3_lifecycle_configuration.py
tests/rules/test_S3LifecycleConfigurationRule.py
tests/test_templates/rules/S3LifecycleConfiguration/allowed_template_malformed_lifecycle_rules.yaml
tests/test_templates/rules/S3LifecycleConfiguration/bad_template_no_configurations.yaml
tests/test_templates/rules/S3LifecycleConfiguration/good_template.yaml

New rule to check for the presence of the `LifecycleConfiguration` property on S3 buckets, which can be useful for data retention policies, compliance, and reducing AWS costs.

S3LifecycleConfiguration rule

---

CHANGELOG.md
cfripper/__version__.py
cfripper/config/regex.py
cfripper/rules/wildcard_principals.py
tests/config/test_regex.py
tests/rules/test_GenericWildcardPrincipal.py
tests/rules/test_PartialWildcardPrincipal.py
tests/test_templates/rules/PartialWildcardPrincipalRule/intra_account_root_access.yml

- Add a fix to the `PartialWildcardPrincipal` rule to be able to detect policies where whole account access is specified via just the account ID.
- For example, if the Principal was defined as `Principal: AWS: 123456789012` as opposed to `Principal: AWS: arn:aws:iam::123456789012:root`.
- These are identical: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html

PartialWildcardRule to detect usage of just account IDs in the principal

---

CHANGELOG.md
cfripper/__version__.py
cfripper/config/config.py
cfripper/config/rule_configs/allow_http_ports_open_to_world.py
cfripper/config/rule_configs/example_rules_config_for_cli.py
cfripper/rules/ec2_security_group.py
tests/rules/test_EC2SecurityGroupOpenToWorldRule.py
tests/test_templates/rules/EC2SecurityGroupOpenToWorldRule/invalid_security_group_port78_81.json

This PR removes exemptions that were being applied to the following two rules:
* EC2SecurityGroupOpenToWorldRule
* EC2SecurityGroupIngressOpenToWorldRule
If these security groups were open to ports 80 or 443, they did not fail the check. This was hardcoded configuration in CFRipper. Moving forwards, we should be using the concept of filters to make this exemption optional.
* Remove existing hardcoded configuration around ports 80 and 443
* Create a new filter that preserves the logic of this change, but can be optionally applied (or supplemented with other conditions in the filter, depending on the use case)
* Update rules to handle the removal of the hardcoded configuration
* Update unit tests
This change will be released in version 1.2.0.

Remove default exemption for ports 80 and 443 on Open Security Group rules

---

.gitignore
CHANGELOG.md
cfripper/__version__.py
cfripper/rules/wildcard_resource_rule.py
tests/rules/test_WildcardResourceRule.py
tests/test_templates/rules/WildcardResourceRule/policy_with_invalid_string_policy_document.json
tests/test_templates/rules/WildcardResourceRule/policy_with_string_policy_document.json

This PR implements a fix for the `WildcardResourceRule` where it would fail on policy documents of type string.
Example error:
```
Traceback (most recent call last):
File "/var/task/cfripper/rule_processor.py", line 24, in process_cf_template
result += rule.invoke(cfmodel, extras)
File "/var/task/cfripper/rules/base_rules.py", line 104, in invoke
result += self.resource_invoke(resource=resource, logical_id=logical_id, extras=extras)
File "/var/task/cfripper/rules/wildcard_resource_rule.py", line 63, in resource_invoke
self._check_policy_document(result, logical_id, PolicyDocument(**policy_document), None, extras)
TypeError: pycfmodel.model.resources.properties.policy_document.PolicyDocument() argument after ** must be a mapping, not str
```
Unit tests added. Bumped version to 1.2.1.

Add support for policy documents that are of type string in WildcardResourceRule

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/__init__.py
cfripper/rules/cross_account_trust.py
requirements.txt
setup.py
tests/rules/test_CrossAccountTrustRule.py
tests/test_templates/rules/CrossAccountTrustRule/es_domain_basic.yml
tests/test_templates/rules/CrossAccountTrustRule/invalid_with_sts_es_domain.yml
tests/test_templates/rules/CrossAccountTrustRule/invalid_with_sts_opensearch_domain.yml
tests/test_templates/rules/CrossAccountTrustRule/opensearch_domain_basic.yml
tests/test_templates/rules/CrossAccountTrustRule/valid_with_sts_es_domain.yml
tests/test_templates/rules/CrossAccountTrustRule/valid_with_sts_opensearch_domain.yml

- Add `ElasticsearchDomainCrossAccountTrustRule` and `OpenSearchDomainCrossAccountTrustRule`
- Bump `pycfmodel` to `0.13.0`
Will release `1.3.0` after merging

Add cross account trust rule for ES and OpenSearch domains

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/cross_account_trust.py
tests/rules/test_CrossAccountTrustRule.py
tests/test_templates/rules/CrossAccountTrustRule/es_domain_without_access_policies.yml
tests/test_templates/rules/CrossAccountTrustRule/opensearch_domain_without_access_policies.yml

Fix rule that returned and exception when checking for ES and OpenSearch domains without AccessPolicies

FIX: CrossAccountCheckingRule checking resources without PROPERTY_WITH_POLICYDOCUMENT

---

CHANGELOG.md
cfripper/__version__.py
requirements.txt
setup.py

- Bump `pycfmodel` to `0.16.3`

Bump pycfmodel to 0.16.3

---

CHANGELOG.md
Makefile
cfripper/__version__.py
setup.py

- Fix how `make install-dev` works, it will install dependencies from `make install` first.
- Bump dev dependency `moto` from `1.3.13` to `1.3.14`.

Fix how make install-dev works

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/ebs_volume_has_sse.py
requirements.txt
setup.py
tests/rules/test_EBSVolumeHasSSERule.py
tests/test_templates/rules/EBSVolumeHasSSERule/bad_template.yaml

- `EBSVolumeHasSSERule` can now understand `encrypted_status` if modelled as a `bool`.
- Updated `EBSVolumeHasSSERule` to iterate only over `AWS::EC2::Volume` resources.

Fix EBSVolumeHasSSERule for bool type

---

CHANGELOG.md
cfripper/__version__.py
cfripper/cli.py
cfripper/rules/__init__.py
cfripper/rules/ec2_security_group.py
pyproject.toml
requirements.txt
setup.cfg
setup.py
tests/model/test_principal_checking_rule.py
tests/rules/test_CrossAccountTrustRule.py
tests/rules/test_EBSVolumeHasSSERule.py
tests/rules/test_EC2SecurityGroupIngressOpenToWorld.py
tests/rules/test_EC2SecurityGroupOpenToWorldRule.py
tests/rules/test_GenericCrossAccountTrustRule.py
tests/rules/test_GenericResourceWildcardPolicyRule.py
tests/test_boto3_client.py
tests/test_cli.py

- Pin `click` to at least version `8.0.0`.
- Update `black` to `22.3.0`, and run `make format` with this new version of `black`.

Pin `click` to at least version 8 and update `black` to 22.3.0

---

cfripper/cli.py

https://sourcegraph.com/search?q=r:Skyscanner/cfripper+.info
[`WildcardResourceRule`](https://cfripper.readthedocs.io/en/latest/rules/#wildcardresourcerule) in particular can generate a lot of non-actionable noise:
https://github.com/Skyscanner/cfripper/blob/3c7b068db6bf130f113a5ba9271100c6292d14e2/cfripper/rules/wildcard_resource_rule.py#L134-L140

default logging level from INFO to WARNING

---

CHANGELOG.md
cfripper/__version__.py
cfripper/rules/cross_account_trust.py
cfripper/rules/wildcard_principals.py
tests/rules/test_GenericCrossAccountTrustRule.py
tests/rules/test_GenericResourcePartialWildcardPrincipal.py

- Fixes `GenericResourcePartialWildcardPrincipalRule` and `GenericCrossAccountTrustRule` message, since sometimes it was bad-formatted in markdown.

Fix bad formatting in generic rules messages

---

cfripper/rules/rds_security_group.py

Docs are broken, see: https://cfripper.readthedocs.io/en/latest/rules/#rdssecuritygroupingressopentoworldrule

Fix rds_security_group.py docs

---

cfripper/rules/base_rules.py

Fix to update a typo in the class documentation.
In the code, for example in https://github.com/Skyscanner/cfripper/blob/master/cfripper/rules/base_rules.py#L201 we can see how "actions" instead of "action" is used.

Fix typo in base_rule actions

---

cfripper/config/regex.py
cfripper/rules/__init__.py
cfripper/rules/stack_name_matches_regex.py
tests/rules/test_StackNameMatchesRegexRule.py

We add a new rule that checks whether the stack name only consists of alphanumerical characters and hyphens.

Create stack name example rule

---

.github/release-drafter.yml
CHANGELOG.md
cfripper/__version__.py
cfripper/rules/kms_key_wildcard_principal.py
requirements.txt
setup.py
tests/rules/test_CrossAccountTrustRule.py
tests/rules/test_KMSKeyWildcardPrincipal.py
tests/rules/test_WildcardResourceRule.py
tests/test_templates/rules/CrossAccountTrustRule/kms_key_without_policy.yml
tests/test_templates/rules/KMSKeyWildcardPrincipalRule/kms_key_with_wildcard_resource.json
tests/test_templates/rules/KMSKeyWildcardPrincipalRule/kms_key_without_policy.yml

- Fix KMSKeyWildcardPrincipalRule to work without a KMS policy
- Add tests
- Fix release drafter template

Bump pycfmodel and fix KMSKeyWildcardPrincipalRule

---

README.md

Logo is broken in https://pypi.org/project/cfripper/
According to https://github.com/pypi/warehouse/issues/5246 using the url fixes it.
Readme is still looking good https://github.com/Skyscanner/cfripper/tree/fix_pypi_logo

Fix logo in pypi

---

.github/workflows/pypi-release.yml

I'm creating this PR because we're introducing GitHub Actions as a trusted publisher to the cfripper library. Here, we're making an update to the pypi-release workflow so we remove the username and password as this is not needed.

Removed user and password from pypi-release.yml

---

cfripper/cloudformation_actions_only_accepts_wildcard.py

Certificate Manager does not support resource level IAM when requesting certificates, see https://docs.aws.amazon.com/service-authorization/latest/reference/list_awscertificatemanager.html.

Add `RequestCertificate` to wildcard whitelist

---

cfripper/boto3_client.py

This small PR resolves the `datetime` deprecation warnings which you can see in the [CI logs](https://github.com/Skyscanner/cfripper/actions/runs/14666499624/job/41162481548#step:6:1770):
```python
/home/runner/work/cfripper/cfripper/cfripper/boto3_client.py:25: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
now = datetime.utcnow().isoformat().replace(":", ".")
```

Resolve datetime deprecation warnings

---

.github/workflows/codeql.yml
CHANGELOG.md
cfripper/model/utils.py
tests/config/test_config.py
tests/rules/test_CrossAccountTrustRule.py

Create Code Scanning workflow in codeql.yml
Copy-Pasting the config from pycfmodel (sibling repo): https://github.com/Skyscanner/pycfmodel/blob/master/.github/workflows/codeql.yml
Solving low-warning "Note" issues surfaced during the scans.

Create codeql.yml workflow

---

CHANGELOG.md
cfripper/cloudformation_actions_only_accepts_wildcard.py
cfripper/rules/base_rules.py
tests/config/test_filter.py

Truncate reason field to avoid overloading metrics logger

Truncate reason in metrics logger
