- cfripper/config/config.py
- cfripper/main.py
Adding the CF event type in the lambda event and then the config.
> Add CF event

- cfripper/config/whitelist.py
- tests/test_config.py
Add wildcard support for rule whitelisting
> Add wildcard support for rule whitelisting

- cfripper/config/config.py
- cfripper/main.py
> Add template url to config

- README.md
- cfripper/rules/S3CrossAccountTrustRule.py
- cfripper/rules/__init__.py
- requirements.txt
- tests/test_s3_cross_account.py
- tests/test_templates/s3_bucket_cross_account.json
- tests/test_templates/s3_bucket_cross_account_and_normal.json
Add S3CrossAccount rule to list of rules. In monitor mode.
> Add S3CrossAccount rule to list of rules. In monitor mode.

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Add code of conduct.
Also clear up the license formatting to be more Python-friendly.
> [NO-JIRA] Add code of conduct

- cfripper/rules/S3BucketPolicyPrincipalRule.py
Context
--------
Promoting S3BucketPolicyPrincipalRule to blocking mode
> block mode

- setup.py
Last change added a new feature to one of the rules, this needs a version bump (0.7.1 to 0.7.2)
> Bump version after last change

- CHANGELOG.md
- setup.py
Release commit. Updates setup.py and CHANGELOG
> Update setup.py and CHANGELOG

- README.md
Just added some readme information about the installation. Ref: #66 
Thank you guys.
> Lambda Installation Readme

- CHANGELOG.md
- cfripper/boto3_client.py
- requirements.txt
- setup.py
- tests/test_boto3_client.py
> Fix get_template method from boto3_client

- cfripper/config/regex.py
- cfripper/rules/cloudformation_authentication.py
- cfripper/rules/cross_account_trust.py
- cfripper/rules/ebs_volume_has_sse.py
- cfripper/rules/hardcoded_RDS_password.py
- cfripper/rules/iam_managed_policy_wildcard_action.py
- cfripper/rules/iam_roles.py
- cfripper/rules/kms_key_wildcard_principal.py
- cfripper/rules/managed_policy_on_user.py
- cfripper/rules/policy_on_user.py
- cfripper/rules/privilege_escalation.py
- cfripper/rules/s3_bucked_policy.py
- cfripper/rules/s3_public_access.py
- cfripper/rules/security_group.py
- cfripper/rules/sns_topic_policy_not_principal.py
- cfripper/rules/sqs_queue_policy.py
- cfripper/rules/wildcard_principals.py
- docs/macros.py
- docs/rules.md
- requirements.txt
- tests/config/test_regex.py
> Improve rule docs

- CHANGELOG.md
Update release date in CHANGELOG.md
> Release 0.12.0

- README.md
> Add LGTM badges to readme

- CHANGELOG.md
- cfripper/__version__.py
- cfripper/model/utils.py
- tests/model/test_utils.py
- Add support for this new S3 URL format: `https://bucket.s3.aws-region.amazonaws.com/path1/path2`
> Support new S3 URL format

- Makefile
- requirements.txt
- Adds no annotate flag to pip-compile
- Removes lambda.zip and clean instructions from makefile
- Updates requirements
> Update makefile & requirements.txt

- cfripper/rule_processor.py
- cfripper/rules/base_rules.py
- tests/model/test_rule_processor.py
Feature: don't run disabled rules
> Feature: don't run disabled rules

- CHANGELOG.md
- cfripper/config/rule_configs/firehose_ips.py
- cfripper/model/enums.py
- cfripper/rules/base_rules.py
- cfripper/rules/cross_account_trust.py
- cfripper/rules/s3_bucket_policy.py
- cfripper/rules/wildcard_principals.py
- tests/config/test_filter.py
- tests/conftest.py
- tests/model/test_principal_checking_rule.py
- tests/rules/test_CrossAccountTrustRule.py
- tests/rules/test_EC2SecurityGroupIngressOpenToWorld.py
- tests/rules/test_EC2SecurityGroupMissingEgressRule.py
- tests/rules/test_EC2SecurityGroupOpenToWorldRule.py
- tests/rules/test_S3BucketPolicyPrincipalRule.py
- tests/test_files/config/rules_config_invalid.py
- tests/test_files/filters/test_filter_1.py
- tests/test_files/invalid_filters/invalid_filters.py
> Rename whitelisted to allowed

- cfripper/rules/cross_account_trust.py
- cfripper/rules/privilege_escalation.py
- cfripper/rules/wildcard_principals.py
- tests/config/test_config.py
- tests/model/test_principal_checking_rule.py
- tests/rules/test_WildcardResourceRule.py
- tests/test_templates/rules/GenericWildcardPrincipalRule/wildcard_principal_rule_is_allowed_retrieved_correctly.json
- tests/utils.py
> Rename whitelist Part2

- cfripper/model/result.py
Change to collection get_failures parameters type
> Change to collection get_failures parameters type

- cfripper/boto3_client.py
- cfripper/main.py
- tests/test_boto3_client.py
- tests/test_main.py
Add export values from stacks in a given account and region to be used in resolving CF stacks
> Add `get_exports` function to get export values from AWS

- .github/workflows/lint-and-test.yml
> Run tests for python 3.9

- README.md
> make logo centered

- Makefile
This also helps if you setup a local virtual env to remove spurious results
> Refactor unused SOURCES var in Makefile to explicitly reference all sources

- tests/test_templates/rules/WildcardResourceRule/iam_policy_with_wildcard_resource_and_wildcard_action_and_condition.json
> Fix failing test_WildcardResourceRule.py::test_policy_document_with_condition_is_ignored

- CHANGELOG.md
- cfripper/__version__.py
- cfripper/rules/__init__.py
- cfripper/rules/s3_public_access.py
- tests/rules/test_S3BucketPublicReadAclRule.py
- tests/test_templates/rules/S3BucketPublicReadAclRule/bad_template.json
Add S3BucketPublicReadAclRule rule. Checks if a bucket has `PublicRead` ACL
> Add S3BucketPublicReadAclRule rule

- CHANGELOG.md
- cfripper/config/regex.py
- cfripper/rules/wildcard_resource_rule.py
- tests/config/test_regex.py
- tests/rules/test_WildcardResourceRule.py
- tests/test_templates/rules/WildcardResourceRule/policy_with_s3_wildcard_and_all_buckets.json
This change makes it possible to detect policies like this one:
```yaml
- Action:
- s3:*
Effect: Allow
Resource:
- arn:aws:s3:::*
```
> Wildcard service improvements

- CHANGELOG.md
- cfripper/__version__.py
- cfripper/rules/__init__.py
- cfripper/rules/s3_lifecycle_configuration.py
- cfripper/rules/s3_object_versioning.py
- cfripper/rules/s3_public_access.py
- requirements.txt
- setup.py
- tests/rules/test_S3ObjectVersioningRule.py
- tests/test_templates/rules/S3CrossAccountTrustRule/s3_bucket_cross_account.json
- tests/test_templates/rules/S3CrossAccountTrustRule/s3_bucket_cross_account_and_normal.json
- tests/test_templates/rules/S3CrossAccountTrustRule/s3_bucket_cross_account_from_aws_service.json
- tests/test_templates/rules/S3ObjectVersioning/good_template.yaml
- tests/test_templates/rules/S3ObjectVersioning/no_versioning_defined.yaml
- tests/test_templates/rules/S3ObjectVersioning/status_suspended.yaml
Add S3ObjectVersioning rule to CFRipper. Tests updated.
> Add S3ObjectVersioning rule to CFRipper

- cfripper/__version__.py
Will re-release `1.2.2` after this merge
> Fix version

- CHANGELOG.md
- cfripper/__version__.py
- cfripper/rules/cross_account_trust.py
- cfripper/rules/kms_key_wildcard_principal.py
- cfripper/rules/s3_bucket_policy.py
- cfripper/rules/sqs_queue_policy.py
- cfripper/rules/wildcard_principals.py
Stop logging when conditions are ignored.
> Stop logging when conditions are ignored

- CHANGELOG.md
- cfripper/__version__.py
Updates version and changelog accordingly
> Prepare next version

- .github/workflows/pypi-release.yml
- CHANGELOG.md
- Updated changelog for missing updates from old PRs
- Created new token
- Updated workflow based on errors seen in: https://github.com/Skyscanner/cfripper/actions/runs/6324706372/job/17174717761
> Fix release workflow

- CHANGELOG.md
- cfripper/__version__.py
- cfripper/config/config.py
Improve Filter handling code to make it easier to do dynamic imports.
> Refactor filter methods

- .github/workflows/lint-and-test.yml
- .github/workflows/pypi-release.yml
- .github/workflows/test-docs.yml
Bump actions to v4 to solve some warnings
> Bump actions

- CHANGELOG.md
- cfripper/__version__.py
Bump version to fix the documentation.
> Bump version to 1.15.1

- README.md
Add Homebrew badge (if you click it, it goes to: https://formulae.brew.sh/formula/cfripper)
Update HTML in image in the readme, see it in: https://github.com/Skyscanner/cfripper/tree/add-homebrew-badge
> Add Homebrew badge

- CHANGELOG.md
Remove duplicated section in the changelog
> Remove duplicated section in Changelog

- CHANGELOG.md
- cfripper/__version__.py
Update version file and changelog
> Hotfix version file and changelog

- CHANGELOG.md
- cfripper/config/filter.py
- docs/rule_config_and_filters.md
- tests/config/test_filter.py
This new methods make it possible to simplify filter creation.
> Adding set and sort filter functions

- .github/workflows/release-drafter.yml
Use a GitHub App for access to the GitHub REST API as a workaround for [limitations with IP allowlisting](https://docs.github.com/en/enterprise-cloud@latest/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/managing-allowed-ip-addresses-for-your-organization#using-github-actions-with-an-ip-allow-list).
(not applicable / no functionality changes)
> SDPLAT-26993: use GH_APP for GitHub REST API

- .github/workflows/pypi-release.yml
- CHANGELOG.md
Revert back to token auth based for pypi.
> Revert back to token auth based for pypi

- CHANGELOG.md
- cfripper/config/config.py
> Add support for repo_name
